Added Kungfu Panda
akanshSirohi/Github-Cards-API pull request #104
Opened 2024-10-16 04:12 UTC by ashwinshawntauro

Added:
- Card: Kungfu Panda 
- Theme: pandaLight, pandaDark

2024-10-16 17:23 UTC, akanshSirohi commented on src/data/kungfu_panda_quotes.json
@ashwinshawntauro Please add at-least 100 entries to your card.

2024-10-16 17:23 UTC, akanshSirohi commented on src/themes.js
@ashwinshawntauro Please try to change the required code only, modifying the whole code is not necessary.

2024-10-16 17:24 UTC, akanshSirohi requested changes
@ashwinshawntauro Please do the changes requested.

2024-10-17 02:33 UTC, ashwinshawntauro commented on src/themes.js
@akanshSirohi Only changed card details and theme

2024-10-20 17:27 UTC, akanshSirohi requested changes
@ashwinshawntauro Please do the requested changes

2024-10-20 17:27 UTC, akanshSirohi commented on src/themes.js
@ashwinshawntauro You still have not fixed this file, you have added alot of changes which I am unable to check. Please add only required changes so I can verify. Please do not format whole file.

2024-10-20 17:27 UTC, akanshSirohi commented
@ashwinshawntauro Also please resolve conflicts in your branch

2024-10-27 11:33 UTC, closed without merging