Breaking bad quotes
akanshSirohi/Github-Cards-API pull request #70
Opened 2024-10-09 13:31 UTC by HritvikBhatia

"Breaking Bad Quotes" block to the project. This block showcases popular quotes from the iconic television series "Breaking Bad," enhancing the application with engaging and memorable content for users.

2024-10-09 13:35 UTC, HritvikBhatia commented
![Screenshot 2024-10-09 190410](https://github.com/user-attachments/assets/20107e2c-de1c-4d73-ae4b-eae4dfe01b6e)

2024-10-09 17:14 UTC, akanshSirohi requested changes
@HritvikBhatia Please don't remove any file in this PR, undo yarn.lock deletion in this PR and add at least 100 entries in your card.

2024-10-10 01:56 UTC, HritvikBhatia commented
@akanshSirohi done sir

2024-10-10 18:07 UTC, akanshSirohi approved these changes

2024-10-10 18:07 UTC, merged