game of thrones quotes
akanshSirohi/Github-Cards-API pull request #77
Opened 2024-10-10 03:15 UTC by HritvikBhatia

Proposal: #76 

Changes Made
Added a JSON file containing 100 quotes from Game of Thrones.
Created a display card section to render the quotes on the page.

![Screenshot 2024-10-10 083312](https://github.com/user-attachments/assets/78f06249-0b0e-4473-9062-101c164b9303)

2024-10-10 18:14 UTC, akanshSirohi requested changes
@HritvikBhatia Please resolve conflicts in your PR

2024-10-11 01:03 UTC, HritvikBhatia commented
@akanshSirohi done sir

2024-10-11 17:44 UTC, akanshSirohi requested changes
@HritvikBhatia Please add your card to readme.md too.

2024-10-11 19:31 UTC, HritvikBhatia commented
@akanshSirohi done sir 😸😺

2024-10-12 17:24 UTC, akanshSirohi commented on README.md
@HritvikBhatia  Check the line 67, you have added some extra text ":wq" looks like you were trying to use vim. I have fixed it but please check your PR from next time properly.

2024-10-12 17:24 UTC, akanshSirohi approved these changes

2024-10-12 17:25 UTC, merged