French Word Of The Day Card
akanshSirohi/Github-Cards-API pull request #95
Opened 2024-10-13 13:59 UTC by Chhavi9700225780

May this new Card feature will help developers through your GitHub Card API . If you like this feature pls merge my Pull request under hactoberfest 2024.
Thanking you.

2024-10-13 18:24 UTC, akanshSirohi commented on src/cards/breaking-bad-quotes.js
Please check your commit properly before pushing it, this file has just line added and you pushed it.

2024-10-13 18:30 UTC, akanshSirohi requested changes
Please make the required changes
1. Fix the card age, as this will make more sense
2. Add more entries to your card data.

2024-10-13 18:30 UTC, akanshSirohi commented on src/data/french_word_of_the_day.json
@Chhavi9700225780 Please add more entries, atleast 100 entries required for a card.

2024-10-13 18:30 UTC, akanshSirohi commented on src/cards/french_word_of_the_day.js
@Chhavi9700225780 Just a suggestion for you, this is the card of the day, so you can change the default value of CARD_AGE and extend it to a day so it won't change for a user before a day.

2024-10-14 10:49 UTC, Chhavi9700225780 commented on src/data/french_word_of_the_day.json
@akanshSirohi 
I have added 200 entries now could you pls check it again if it is okay then pls merge my pull request under hactoberfest 2024 .
Thanking you!!

2024-10-14 10:55 UTC, Chhavi9700225780 commented on src/cards/french_word_of_the_day.js
@akanshSirohi could you pls guide me a little in this feature . Should I change the value of card equal to one so that it won't change for a user before a day.

2024-10-14 17:16 UTC, akanshSirohi commented on src/cards/french_word_of_the_day.js
Check this out: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

2024-10-14 17:17 UTC, akanshSirohi commented on src/cards/french_word_of_the_day.js
@Chhavi9700225780 You just need to modify a number that is it.

2024-10-14 17:17 UTC, akanshSirohi commented on src/cards/french_word_of_the_day.js
@Chhavi9700225780 I am not merging this branch for now, you can make your changes then I will do.

2024-10-15 17:47 UTC, merged